### ISSUE TITLE
I'm getting an error, can anyone help me?

### ISSUE THREAD

**Issue by nht-spect** [lucascouto/krackattack-all-zero-tk-key#11]
![198484231_1368018363597532_2790494009450307320_n](https://user-images.githubusercontent.com/82362395/122067811-13b67f00-ce1e-11eb-8f29-bcacf626b642.png)

**Comment by Real96** [comment]
Did you install scapy? Are you using python2?
Also, use scapy 2.3.3

**Comment by ChillVibesMushroom** [comment]
when I run pip install scapy==2.3.3  I recieve this error

Collecting scapy==2.3.3
  Using cached scapy-2.3.3.tgz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w8ok0hx3/scapy_80c77e7766dd49bd9998cc02c8967f13/setup.py", line 36
          os.chmod(fname, 0755)
                          ^
      SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.



I have everything else ready and working

**Comment by ChillVibesMushroom** [comment]
sudo ./krack_all_zero_tk.py -h                                             
Traceback (most recent call last):
  File "./krack_all_zero_tk.py", line 15, in <module>
    from scapy.all import *
ImportError: No module named scapy.all
